# Generated by Django 3.1 on 2021-01-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='components',
        ),
        migrations.RemoveField(
            model_name='data',
            name='d_id',
        ),
        migrations.RemoveField(
            model_name='data',
            name='imagePath',
        ),
        migrations.AddField(
            model_name='data',
            name='Application',
            field=models.CharField(max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='BackgroundImage',
            field=models.TextField(max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='Button',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='Columns',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='Components',
            field=models.CharField(max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='Description',
            field=models.CharField(max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='Form',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='Icon',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='ListType',
            field=models.CharField(max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='Name',
            field=models.CharField(max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='PageType',
            field=models.CharField(max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='Paragraph',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='Remarks',
            field=models.CharField(max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='SiteType',
            field=models.CharField(max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='Title',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='Video',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='image',
            field=models.IntegerField(null=True),
        ),
    ]
