# Generated by Django 3.1 on 2021-01-20 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0003_data_d_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='Button',
            new_name='paragraph',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Application',
        ),
        migrations.RemoveField(
            model_name='data',
            name='BackgroundImage',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Columns',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Components',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Form',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Icon',
        ),
        migrations.RemoveField(
            model_name='data',
            name='ListType',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='data',
            name='PageType',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Paragraph',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Remarks',
        ),
        migrations.RemoveField(
            model_name='data',
            name='SiteType',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Video',
        ),
        migrations.RemoveField(
            model_name='data',
            name='d_id',
        ),
    ]
