# Generated by Django 3.1 on 2021-01-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0004_auto_20210120_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='paragraph',
            new_name='no_of_paragraph',
        ),
    ]
