# Generated by Django 3.1 on 2021-01-22 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0005_auto_20210120_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='no_of_paragraph',
            new_name='Text',
        ),
    ]
