# Generated by Django 3.1 on 2021-01-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0008_auto_20210122_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Image',
            new_name='Img',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='Text',
            new_name='Txt',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='Title',
            new_name='Tit',
        ),
    ]
