# Generated by Django 3.1 on 2021-01-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0009_auto_20210125_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Index', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
