# Generated by Django 3.1 on 2021-01-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0012_pagetype_sitetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Describe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sitetype',
            name='sitetype',
        ),
        migrations.AddField(
            model_name='sitetype',
            name='Listing',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
