# Generated by Django 3.1 on 2021-02-08 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0015_verifiedby_verifieddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='describe',
            old_name='describe',
            new_name='Describe',
        ),
    ]
