# Generated by Django 3.1 on 2021-02-08 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapper', '0016_auto_20210208_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='describe',
            old_name='Describe',
            new_name='des',
        ),
    ]
